### ISSUE TITLE
[Bug]: Retention Policy Filtering SetSelectedSystemId

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/BCApps#1947]
### Describe the issue

In the Codeunit 3915 "Reten. Pol. Filtering Impl." in the procedure SetSelectedSystemId the else statement is on the wrong ir-statement. It should be for `if IsSelected then` and not for `if not SelectedSystemIds.ContainsKey(SelectedSystemId) then`.

https://github.com/microsoft/BCApps/blob/832c37a2fee659ce038c48d9016eebf610ebfcaa/src/System%20Application/App/Retention%20Policy/src/Apply%20Retention%20Policy/RetenPolFilteringImpl.Codeunit.al#L276

This influences the record counter and could lead to the wrong wrong outcome of the retention policy deletion.
For example many customers and partners have problem with the change log and maybe this could solve the issue. 

I think the list gets longer and even when removing the entries to delete, it will not be removed instead kept in the list to delete. Because the marks get removed but not the buffer, the counter gets wrong in the `ApplyRetentionPolicySubSetFilters` procedure of the same codeunit.

https://github.com/microsoft/BCApps/blob/832c37a2fee659ce038c48d9016eebf610ebfcaa/src/System%20Application/App/Retention%20Policy/src/Apply%20Retention%20Policy/RetenPolFilteringImpl.Codeunit.al#L120

### Expected behavior

The counter should be updated correct.

### Steps to reproduce

.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by grobyns** [comment]
@BernhardKloibmueller 
I created a branch with a fix because i want to run our tests with the fix and cannot do it without a branch. I did not want to step on your toes, so sorry for jumping the gun... 
Of course you might not like my fix and want to do it another way, that's fine :-) ... or if you do like it, we can make the PR on that branch and get the fix in ;-)

**Comment by grobyns** [comment]
@BernhardKloibmueller 
while running tests I got some failures. I do not know if they were there before or if they are due to this fix. I'm looking into it, so while the issue is approved and I think you are correct about the bug and fix, maybe hold off until I get to the bottom of these issues.

OR, if you take a look at the branch i linked and agree with that fix, just let me know and i'll take it from here. 

cheers,
Gert

**Comment by BernhardKloibmueller** [comment]
@grobyns 
Your change seems valid and should work.
If you need to do more changes so it will work please proceed and let me know if I have to do something. If not I will myself proceed just like discussed on yammer to investigate our behavior. But this will take some time.
