### ISSUE TITLE
[Bug]: Reuse of code in "No. Series - Stateless Impl." and "No. Series - Sequence Impl." codeunits is not possible

### ISSUE THREAD

**Issue by ThomasBrodkorb** [microsoft/BCApps#2034]
### Describe the issue

We have an extension we are in the process to publish to AppSource, we extend number creates by number series with checksums.
Therefore it is required to modify the "Last Number Used" return by the "No. Series" codeunit.
We do like the idea to use interfaces for this.
Unfortunatley it is not possible to call the procedures in CU 306 and 307 from our implementation of the "No. Series - Single" interface as the CUs 306 and 307 are marked as "Access = Internal"
Of course it would be possible to just duplicate the codeunits and use the copies for our implementation, but we think, this is not the best solution.
In case a bug is detected or the functionality in those codeunits is extended, we would have to copy these modifications over as well. This means an increaesed effort to maintain the code.
It would be easier to allow public access to these codeunits instead.

### Expected behavior

CU 306 and cu 307 as Access = Public

### Steps to reproduce

crate a procedure and a var of type codeunit 306.

Call any public procedure

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by grobyns** [comment]
I will look into this more closely but as first impressions, impl. codeunits are internal by design and for a reason. I will not make them public.

Second, most of the post doesn’t describe the issue but rather describes how you’d like it fixed. That’s not much for me to go on as there’s not much room for alternatives.

What I can say is that before v24 you could get a number from the code and change it, to basically anything. The new code doesn’t allow this, by design. The setup describes a pattern. You ask for a number using that pattern. Then, you want to change it, now the number no longer fits the pattern that was set up. We no longer support this in std code, but of course it is doable through a custom implementation.

Is the original number saved in Last Number Used or the one with checksum? Or do you maybe save both (in an extra field?).

Not ideal, but you could pass a temporary record to the facade and change the enum to have it call standard code and then take the resulting number and record, add the checksum and copy it to the real table… you’d need to be careful with locking to avoid issues but it should be doable…

I’ll look into the code reusability issue to see where that might make sense.

**Comment by ThomasBrodkorb** [comment]
I'm sorry, this is the first issue report I ever wrote in 25 years of NAV and BC programming, so bear with me, if it was not described the way you expected.

Let me describe the issue (even though it seems you already got it the way I meant it):

In the previous versions, events were available to amend the number before returning it (namely OnAfterGetNextNo3 in CU NoSeriesMgt).
With this, it was possible to change the number returned (like adding a checksum) before returning to the calling code without saving the modified "Last No. Used" field content to the "No. Series Line".
These events do not exist in the "No. Series" codeunits altogether.
So the number generated still follows the pattern defined, but adds one additional character at the end.
So the generation of the new number - according to the stateless or sequence method - stays exactly as is. So the standard code in CU 306/307 (and maybe more in the future) is just perfect for what we want to achieve. We just need to append a checksum to the numbers generated for invoice numbers, credit memo numbers, barcode numbers and so on.


There is a number of solutions I can imagine which do allow the same manipulation of the number returned:

1. Reintroduce events in Codeunit 310 "No. Series" or Codeunit 396 NoSeriesManagement
2. Make CU 306/307 Facade codeunits and make those public, move implementation code to new codeunits.
3. Create new facade and implementation codeunits for 306/307 as pure interface implementations and let 306 call the facade 311 "No. Series - Stateless" which is Access = Public" and move current 306 functionality into CU 312 "No. Series Impl. - Stateless ".
4. Create two new codeunits which implement the "No. Series - Single" interface and make them Access = Public.
Call the cu 306/307 from there. Remove the "implements No. Series - Single"  from the CU 306/307

I'm pretty sure, there are additional ideas, but that should give a range of options to consider and find the best solution.

For now, we will create a new codeunit and just duplicate the complete code from 306/307 codeunits and add the code we need.
I am sure that that is the worst option we have and I always prefer to reuse standard functionality as much as possible to stay with the standard as close as possible.
This also helps to prevent problems as our code would benefit directly from any bug fixes and improvements you apply to the standard objects.

**Comment by grobyns** [comment]
@ThomasBrodkorb 
For your scenario, I think extending the enum and providing a separate implementation is the better approach. Some No. Series get 'normal' treatment, other get 'extra' treatment... Using an event here is less desirable because you'd need to be called every time and then in the subscriber decide whether or not it applies... 

As I mentioned earlier, you can re-use the code by calling the "No. Series" codeunit in your new Impl. codeunit. If you look into the "No. Series - Batch Impl." codeunit, you see it also does this. 

In your case how this might play out is: 
Some code calls NoSeries.GetNextNo. The code does some validations, gets a line, etc... and then calls your Impl. with a NoSeriesLine. In your implementation you copy the line to a temp, change the Enum and call No. Series codeunit again. You will now get the standard result back, which you save to the normal record and then you apply the checksum.

There is a complication in the current code as we still run some legacy stuff which means the result with checksum would be saved, which you don't want here so after saving, you set the Last No Used to the result with checksum.

Here's the code I came up with, of course this is provided as is and should be very thoroughly tested before use.

[NormalNosWChecksumImpl.Codeunit copy.al.txt](https://github.com/user-attachments/files/17013576/NormalNosWChecksumImpl.Codeunit.copy.al.txt)
[NoSeriesWithChecksum.EnumExt.al.txt](https://github.com/user-attachments/files/17013577/NoSeriesWithChecksum.EnumExt.al.txt)
[SeqNosWChecksumImpl.Codeunit.al.txt](https://github.com/user-attachments/files/17013578/SeqNosWChecksumImpl.Codeunit.al.txt)

**Comment by grobyns** [comment]
There is an issue with (re)using Sequence and that is that our code resets the sequence when you change the implementation enum. To get around that, you have to recreate it, but recreating it every time you use it defeats its purpose... In essence, our code doesn't allow any other implementation to use the SQL sequences... We could improve on that by not resetting if we knew another impl. was going to use the same sequence...

**Comment by ThomasBrodkorb** [comment]
@grobyns  That is not an issue, I would not implement sequences, just the stateless version.
We cannot allow gaps anyway, so NumberSequence would not be working for us.
I will try your implementation suggestion, even though I would have preferred a way to call the original functions directly,
Thank you for your support.
