### ISSUE TITLE
Create Reminders with Include Entries On Hold does not create Reminders if only one customer

### ISSUE THREAD

**Issue by vmilveden** [microsoft/BCApps#324]
Please include the following with each issue:

**1. Describe the bug**
When a new Sales Invoice(overdue) is posted for a Customer that has no overdue Invoices or Reminders and you place a On Hold code on the newly created overdue customer ledger entry.
When trying to create reminders with include entries on hold it does not create a reminder for this newly created overdue customer ledger entry with a On Hold Code, although we have include entries on hold selected.

**2. To Reproduce**

1. Create an overdue Sales Invoice for a Customer that has no overdue Invoices or Reminders, post the invoice.
2. Add value to "On Hold" field on this Customer Ledger Entry
3. Go to Reminders and try to create reminders and Include Entries On Hold (Reminders > Process > Create Reminders)

**3. Expected behavior**
The Reminder is created for the Customer Legder Entry with a On Hold code

**4. Actual behavior**
There is no reminder created.

**5. Versions:**

- AL Language: v12.1887908
- Visual Studio Code: 1.83.1
- Business Central: BC SaaS 23.0.12034.13735-w1

**Comment by pri-kise** [comment]
This repository is currently only for the System Application.

This idea is related to something of the BaseApp.

Therefore the issue should be created at https://github.com/microsoft/BusinessCentralApps (currently private repository; ask @JesperSchulz for access) if you want to solve this problem by yourself @vmilveden - otherwise create a support request via the normal communication channels.

**Comment by JesperSchulz** [comment]
> vmilveden

Please fill out this form, and I will add you to the pilot: https://forms.office.com/r/E9wyE5a58f 😊 As the pilot is in a private repository, I cannot transfer this issue. Hence, please recreate the issue when you have been granted access.
