### ISSUE TITLE
Event Request on Changing Password

### ISSUE THREAD

**Issue by KiprotichKelly** [microsoft/BCApps#328]
**🕮 Describe the issue**
I would like to add an event that allows you to implement password policy on old and new password while changing your user passwords

**🔧 To Reproduce**

The current code only has only one integration event to modify password minimum length only

**📣 Expected behavior**

The current code works fine, this is an additional feature. You can then check that users don't reenter their old passwords asthe new password

**Screenshots**
![image](https://github.com/microsoft/ALAppExtensions/assets/72433703/b8d1ac80-0627-4352-ad5b-3e86ae5c5876)

**Additional context**

**Comment by JesperSchulz** [comment]
@KiprotichKelly, could you look at the question above. Do you still need that event?

**Comment by KiprotichKelly** [comment]
Hello @JesperSchulz, having mentioned the security concern, I think adding the rule to the base app will do for me.

**Comment by JesperSchulz** [comment]
Based on the above, I will approve this issue for contribution :-)

**Comment by Drakonian** [comment]
Since this is still here, can I create a PR?

@JesperSchulz

**Comment by JesperSchulz** [comment]
Absolutely 😊

**Comment by Drakonian** [comment]
@JesperSchulz

Just wondering, in the current implementation the method takes two parameters OldPassword and Password. It is clear about Password, it is a new password that the user sets, but about OldPassword it is not so clear, this field always returns what the user fills in the Old Password field, but it is never set from outside, that is, this field is always empty when opening the password change dialog.
https://github.com/microsoft/BCApps/blob/c651de6aaad69a7ac1e124718d371e5aa9fc94c5/src/System%20Application/App/Password/src/PasswordDialogImpl.Codeunit.al#L71

Which kind of implies that validation of whether the old password was entered correctly is done externally, in the place where this module is called.

Therefore, in order to implement validation inside PasswordDialogManagement it is necessary to pass OldPassword to the Password Dialog page. In such a scenario, the one who uses the OpenChangePasswordDialog method passes OldPassword with the value of the old password from the very beginning, at the moment it is just a Return Value for what the user will enter in the OldPassword field. 

Do you agree with this addition?

**Comment by Drakonian** [comment]
@JesperSchulz in this case it will be two rules

1.Passed OldPassword same as what user fill in Change Password dialog
2.New password is not equal to OldPassword

**Comment by JesperSchulz** [comment]
> @JesperSchulz in this case it will be two rules
> 
> 1.Passed OldPassword same as what user fill to OldPassword field in Change Password dialog 2.New password is not equal to OldPassword

That's how I understand this issue, yes 😊
