### ISSUE TITLE
[BC Idea]: Allow setting SASToken as SecretText in Storage Service Authorization

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/BCApps#895]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=699c8b0d-c3f5-ee11-a73d-6045bd808754

### Description

Currently you can set SASToken only as Text. Adding an overload with a SecretText parameter would allow to secure the value from isolated storage to Auth Codeunit.

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea
Internal work item: [AB#524632](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524632)

**Comment by PJohnstonSysco** [comment]
@ChrisBlankDe - I have some code that uses the Authorize procedure in Codeunit 9088 "Stor. Serv. Auth. Ready SAS". Everything worked ok in V24 but since the changes from this PR have been introduced in V25 the Authorize function returns a blank value. Are you able to test this on your end to check if it is a bug and not just an issue that I am experiencing?
